# app
debug: false

# resources
template_dir: %root_dir%/views
log_dir:      %root_dir%/data/log
cache_dir:    %root_dir%/data/cache
assets_dir:   %root_dir%/assets
web_dir:      %root_dir%/web
twbs_dir:     %root_dir%/vendor/twbs/bootstrap

# twig
twig.path: %root_dir%/views
twig.options:
  cache: %root_dir%/data/cache/twig

# assetic
assetic.path_to_web: %root_dir%/web
assetic.options:
  debug: false
  formulae_cache_dir: %root_dir%/data/cache/assetic
  auto_dump_assets: false

# monolog
monolog.logfile: %root_dir%/data/log/app.log

# dbal
db.options:
  driver:   pdo_mysql
  dbname:   DB_NAME
  host:     DB_HOST
  user:     DB_USER
  password: DB_PASSWORD
  charset:  utf8

# node
node.bin: /usr/bin/node
node.paths:
  - /usr/lib/node_modules

# yui-compressor
yui_compressor.path: /usr/share/yui-compressor/yui-compressor.jar

# orm
orm.proxies_dir: %root_dir%/data/cache/doctrine
orm.em.options:
  mappings:
    - type: annotation
      namespace: App\Entity
      path: %root_dir%/src/App/Entity
